name:                tactic-haskell
version:             0.1.0.0
github:              "totbwf/tactic-haskell"
license:             BSD3
author:              "Reed Mullanix"
maintainer:          "reedmullanix@gmail.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tactic-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2 && < 3
- pretty >= 1.1 && < 1.2
- mtl >= 2 && < 3

library:
  source-dirs: src

tests:
  tactic-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tactic-haskell
