name:                tactic-haskell
version:             0.1.0.0
github:              "totbwf/tactic-haskell"
license:             BSD3
author:              "Reed Mullanix"
maintainer:          "reedmullanix@gmail.com"
copyright:           "2018 Reed Mullanix"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tactic-haskell#readme>

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

dependencies:
- base >= 4.7 && < 5
- pipes >= 4 && < 5
- mmorph >= 1 && < 2
- semigroupoids >= 5 && < 6
- template-haskell >= 2 && < 3
- th-abstraction >= 0.2
- containers >= 0.5 && < 0.6
- text >= 1 && < 2
- prettyprinter >= 1 && < 2
- pretty >= 1.1 && < 1.2
- mtl >= 2 && < 3
- ghc >= 8.4.3 && < 9
- refinery

library:
  source-dirs: src

tests:
  tactic-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tactic-haskell
